version: "3.5"

networks:
  webnet:
    driver: overlay
    attachable: true
    
    services:
        web:
            build: .
            image: "matisskalnins/cm-backend:v0.0.3"
            deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            ports:
                - "50051:50051"
            env_file:
                - "config/docker.env"

networks: 
    webnet: