name: cm_backend
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  grpc: ^3.0.0
  protobuf: ^2.0.0
  postgres: ^2.3.2
  dotenv: ^3.0.0
  supercharged_dart: ^2.0.0

dev_dependencies:
